version: "3"
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    networks:
      - service_network
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: backend/
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
    networks:
      - service_network
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo_db:27017/admin

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - service_network
    environment:
      - BACKEND_URI=http://backend:3000/tasks

networks:
  service_network:
